global using Microsoft.EntityFrameworkCore;
global using Pastelaria.Core.Settings;
global using System.Reflection;
global using Pastelaria.Core.Interfaces.Base;
global using Pastelaria.Core.Interfaces;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Pastelaria.Core.Models;
global using Pastelaria.Data.Repositories.Base;
